// Thin wrapper around @nostr-dev-kit/ndk: builds the NDK instance, wires the
// configured signer (nsec OR NIP-46 bunker), and exposes a couple of
// convenience methods so tool implementations don't reach into NDK directly.
//
// Signer selection rules:
//   - NOSTR_PRIVATE_KEY set: NDKPrivateKeySigner (hex or nsec). Logged with a
//     stderr warning at startup (see config.ts) recommending NIP-46.
//   - NOSTR_NIP46_URI set: NDKNip46Signer.bunker(...). Accepts the standard
//     `bunker://<pubkey>?relay=...&secret=...` URI format from Amber, nsec.app,
//     Alby Account, etc. Local signer is auto-generated by NDK on first use.
//   - Neither: signer is undefined; the server runs in forced read-only mode
//     (query/decode tools only).

import NDK, {
  type NDKSigner,
  NDKPrivateKeySigner,
  NDKNip46Signer,
} from "@nostr-dev-kit/ndk";
import type { Config } from "./config.js";

export class NdkClient {
  readonly ndk: NDK;
  readonly signer?: NDKSigner;
  private connected = false;
  private signerReady = false;

  constructor(config: Config) {
    this.ndk = new NDK({
      explicitRelayUrls: [...config.NOSTR_RELAYS],
    });

    if (config.NOSTR_PRIVATE_KEY) {
      this.signer = new NDKPrivateKeySigner(config.NOSTR_PRIVATE_KEY);
    } else if (config.NOSTR_NIP46_URI) {
      this.signer = NDKNip46Signer.bunker(this.ndk, config.NOSTR_NIP46_URI);
    }

    if (this.signer) {
      this.ndk.signer = this.signer;
    }
  }

  async connect(): Promise<void> {
    if (this.connected) return;
    await this.ndk.connect();
    this.connected = true;
  }

  hasSigner(): boolean {
    return Boolean(this.signer);
  }

  // For write tools — block until the signer is ready (most relevant for
  // NIP-46, where the bunker handshake completes asynchronously after construction).
  async ensureSignerReady(): Promise<void> {
    if (!this.signer) {
      throw new Error("no signer configured (set NOSTR_PRIVATE_KEY or NOSTR_NIP46_URI)");
    }
    if (this.signerReady) return;
    await this.signer.blockUntilReady();
    this.signerReady = true;
  }

  async getSignerPubkeyHex(): Promise<string | null> {
    if (!this.signer) return null;
    const user = await this.signer.user();
    return user.pubkey;
  }

  // Relay-status snapshot for the `nostr_list_relays` tool.
  relayStatus(): Array<{ url: string; status: string; connected: boolean }> {
    return Array.from(this.ndk.pool.relays.values()).map((r) => ({
      url: r.url,
      status: String(r.status),
      connected: r.connected,
    }));
  }
}
